### 2장 배열 연산 패키지: 넘파이

2.1 자료형

<u>ndarray 생성</u>

array 함수

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])   # int로만 구성
arr2 = np.array([1, 2, 3.0]) # float 포함
arr3 = np.array([1, 2, '3']) # str 포함

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3] int32
[1. 2. 3.] float64
['1' '2' '3'] <U11


In [2]:
arr1 = np.array([1, 2, 3])                          # 1차원
arr2 = np.array([[1, 2, 3], [4, 5, 6]])             # 2차원
arr3 = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]]) # 3차원

print(arr1.shape) # arr1의 모양 출력
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(1, 4, 2)


arange와 linspace 함수

In [4]:
arr1 = np.arange(5)            # 0부터 5까지 1씩 증가
arr2 = np.arange(-1, 4.5, 1.5) # -1부터 4.5까지 1.5씩 증가
arr3 = np.arange(10, 1, -1)    # 10부터 1까지 -1씩 증가
arr4 = np.linspace(0, 1, 11)   # 0부터 1까지 등간격의 10개의 요소 생성

print("np.arrange(5):{}".format(arr1))
print("np.arrange(-1, 4.5, 1.5):{}".format(arr2))
print("np.arrange(10, 1, -1):{}".format(arr3))
print("np.arrange(0, 1, 11):{}".format(arr4))

np.arrange(5):[0 1 2 3 4]
np.arrange(-1, 4.5, 1.5):[-1.   0.5  2.   3.5]
np.arrange(10, 1, -1):[10  9  8  7  6  5  4  3  2]
np.arrange(0, 1, 11):[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


zeros 함수

In [5]:
arr1 = np.zeros(5)                   # 크기: 5
arr2 = np.zeros((3, 2))              # 크기: (3, 2)
arr3 = np.zeros((2, 2), dtype=bool)  # 크기: (2, 2) 자료형: bool

print(arr1)
print(arr2)
print(arr3)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[False False]
 [False False]]


random 모듈

In [7]:
arr1 = np.random.random(5)
arr2 = np.random.random((2, 2))

print(arr1)
print(arr2)

[0.41230354 0.07090246 0.69556144 0.05706895 0.04041184]
[[0.34285345 0.19146181]
 [0.68384032 0.93659652]]


In [8]:
arr1 = np.random.normal(0, 1, 5)
arr2 = np.random.normal(10, 3, (3, 3))

print(arr1)
print(arr2)

[-0.0576255   0.28147552 -0.22206917 -1.08016544  0.33436527]
[[10.20856265  9.21048326 14.01137065]
 [ 7.36859405  6.68709815 10.49536635]
 [12.39959195 15.182371    4.85330342]]


<u>배열 구조 변경: reshape 메서드</u>

In [9]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.reshape(3, 2))  # (3, 2)로 구조 변경
print(arr2.reshape(-1, 2)) # 열 개수를 2개로 구조 변경
print(arr1.reshape(-1, 1)) # 열 개수를 1개로 구조 변경

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
