### 2장 배열 연산 패키지: 넘파이

2.3 인덱싱과 슬라이싱

<u>기본 인덱싱과 슬라이싱</u>

In [1]:
import numpy as np

x = [[1, 2], [3, 4]]
print(x[0][1])

x = np.array(x)
print(x[0, 1])

2
2


<u>리스트를 활용한 인덱싱과 슬라이싱</u>

In [3]:
x = np.arange(1, 10)
print(x[[0, 3]]) # 0번째 요소와 3번째 요소 인덱싱

[1 4]


In [4]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[0, 1])   # 0행 1열에 있는 값 출력
print(x[[0, 1]]) # 0번째 요소, 1번째 요소 출력

2
[[1 2]
 [3 4]]


In [5]:
x = np.arange(20).reshape(4, 5)
print(x[1, [1, -1]])     # 1번째 행의 1번째 열과 -1번째 열 인덱싱
print(x[0, 0:3])         # 0번째 행의 0번째 열부터 3번째 열까지 슬라이싱
print(x[[0, 1], [2, 3]]) # (0, 2), (1, 3) 셀 인덱싱

[6 9]
[0 1 2]
[2 8]


<u>부울 배열을 활용한 인덱싱과 슬라이싱</u>

In [6]:
x = np.array([1, 2, 3, 4, 5])
b = [True, False, True, True, False]
print(x[b])

[1 3 4]


In [7]:
x = np.array([1, 2, 3, 4, 5])
cond = x >= 3
print(cond)
print(x[cond])

[False False  True  True  True]
[3 4 5]


In [8]:
print(x[x >= 3])

[3 4 5]
