### 3.1 넘파이 배열

3.1.1 배열 생성

In [26]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
type(A)

numpy.ndarray

In [4]:
A.ndim # 배열의 차원

2

In [5]:
A.shape # 배열 크기

(2, 2)

In [6]:
A.dtype # 원소 자료형

dtype('int32')

In [7]:
print(A.max(), A.mean(), A.min(), A.sum())

4 2.5 1 10


3.1.3 배열의 접근

In [10]:
A[0]; A[1]

array([3, 4])

In [12]:
print(A[0][0], A[0][1]); print(A[1][0], A[1][1])

1 2
3 4


In [13]:
print(A[0, 0], A[0, 1]); print(A[1, 0], A[1, 1])

1 2
3 4


In [14]:
A[A>1]

array([2, 3, 4])

3.1.4 배열 형태 바꾸기

In [15]:
A

array([[1, 2],
       [3, 4]])

In [16]:
A.T # A.transpose()와 같다

array([[1, 3],
       [2, 4]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
A.flatten()

array([1, 2, 3, 4])

3.1.5 배열의 연산

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
A + A # np.add(A, A)와 같다

array([[2, 4],
       [6, 8]])

In [21]:
A - A # np.subtract(A, A)와 같다

array([[0, 0],
       [0, 0]])

In [22]:
A * A # np.multiply(A, A)와 같다

array([[ 1,  4],
       [ 9, 16]])

In [23]:
A / A # np.divide(A, A)와 같다

array([[1., 1.],
       [1., 1.]])

3.1.6 브로드캐스팅

In [24]:
A

array([[1, 2],
       [3, 4]])

In [28]:
B = np.array([10,100])

In [29]:
A * B

array([[ 10, 200],
       [ 30, 400]])

3.1.7 내적 구하기

In [30]:
B.dot(B) # np.dot(B, B)와 같다

10100

In [31]:
A.dot(B)

array([210, 430])